# Generated by Django 5.0.14 on 2025-10-01 16:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ua', models.CharField(max_length=255, verbose_name='Назва (UA)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Назва (RU)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Назва (EN)')),
                ('slug_ua', models.SlugField(max_length=255, unique=True, verbose_name='Slug (UA)')),
                ('slug_ru', models.SlugField(max_length=255, unique=True, verbose_name='Slug (RU)')),
                ('slug_en', models.SlugField(max_length=255, unique=True, verbose_name='Slug (EN)')),
                ('show_in_filters', models.BooleanField(default=True, verbose_name='Показывать в фильтрах')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
                'ordering': ['order', 'name_ua'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=255, verbose_name='Заголовок (UA)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('slug_ua', models.SlugField(max_length=255, unique=True, verbose_name='Slug (UA)')),
                ('slug_ru', models.SlugField(max_length=255, unique=True, verbose_name='Slug (RU)')),
                ('slug_en', models.SlugField(max_length=255, unique=True, verbose_name='Slug (EN)')),
                ('content_ua', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент (UA)')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент (RU)')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент (EN)')),
                ('cover', models.ImageField(upload_to='blog/covers/', verbose_name='Обложка')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10)),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
