# Generated by Django 5.0.14 on 2025-10-17 20:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=255, verbose_name='Заголовок (UA)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('description_ua', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (UA)')),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (RU)')),
                ('description_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (EN)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='blog/home/', verbose_name='Hero изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Главная страница блога',
                'verbose_name_plural': 'Главная страница блога',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ua', models.CharField(max_length=255, verbose_name='Назва (UA)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Назва (RU)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Назва (EN)')),
                ('slug_ua', models.SlugField(max_length=255, unique=True, verbose_name='Slug (UA)')),
                ('slug_ru', models.SlugField(max_length=255, unique=True, verbose_name='Slug (RU)')),
                ('slug_en', models.SlugField(max_length=255, unique=True, verbose_name='Slug (EN)')),
                ('show_in_filters', models.BooleanField(default=True, verbose_name='Показывать в фильтрах')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
                'ordering': ['order', 'name_ua'],
                'indexes': [models.Index(fields=['show_in_filters', 'order'], name='blog_blogca_show_in_38416c_idx'), models.Index(fields=['slug_ua'], name='blog_blogca_slug_ua_d51b2a_idx'), models.Index(fields=['slug_ru'], name='blog_blogca_slug_ru_6b150e_idx'), models.Index(fields=['slug_en'], name='blog_blogca_slug_en_c55f0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=255, verbose_name='Заголовок (UA)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('slug_ua', models.SlugField(max_length=255, unique=True, verbose_name='Slug (UA)')),
                ('slug_ru', models.SlugField(max_length=255, unique=True, verbose_name='Slug (RU)')),
                ('slug_en', models.SlugField(max_length=255, unique=True, verbose_name='Slug (EN)')),
                ('content_ua', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (UA)')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание (RU)')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание (EN)')),
                ('cover', models.ImageField(upload_to='blog/covers/', verbose_name='Обложка')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Главное изображение')),
                ('status', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('canonical_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Канонический URL (опционально)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_blogpo_status_aa5436_idx'), models.Index(fields=['slug_ua'], name='blog_blogpo_slug_ua_4df558_idx'), models.Index(fields=['slug_ru'], name='blog_blogpo_slug_ru_6d349e_idx'), models.Index(fields=['slug_en'], name='blog_blogpo_slug_en_cf3035_idx'), models.Index(fields=['published_at', 'created_at'], name='blog_blogpo_publish_be3f2e_idx')],
            },
        ),
    ]
