# Generated by Django 5.0.14 on 2025-10-10 11:03

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=255, verbose_name='Заголовок (UA)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('slug_ua', models.SlugField(max_length=255, unique=True, verbose_name='Slug (UA)')),
                ('slug_ru', models.SlugField(max_length=255, unique=True, verbose_name='Slug (RU)')),
                ('slug_en', models.SlugField(max_length=255, unique=True, verbose_name='Slug (EN)')),
                ('description_ua', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (UA)')),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (RU)')),
                ('description_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (EN)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='blog/home/', verbose_name='Hero изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Главная страница блога',
                'verbose_name_plural': 'Главная страница блога',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Главное изображение'),
        ),
    ]
