# Generated by Django 5.0.14 on 2025-10-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bloghome_blogpost_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloghome',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='bloghome',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='bloghome',
            name='slug_ua',
        ),
    ]
