# Generated by Django 5.0.14 on 2025-10-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_bloghome_slug_en_remove_bloghome_slug_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Главное изображение'),
        ),
    ]
