# Generated by Django 4.2.20 on 2025-10-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_hero_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['show_in_filters', 'order'], name='blog_blogca_show_in_38416c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['slug_ua'], name='blog_blogca_slug_ua_d51b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['slug_ru'], name='blog_blogca_slug_ru_6b150e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['slug_en'], name='blog_blogca_slug_en_c55f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'published_at'], name='blog_blogpo_status_aa5436_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug_ua'], name='blog_blogpo_slug_ua_4df558_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug_ru'], name='blog_blogpo_slug_ru_6d349e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug_en'], name='blog_blogpo_slug_en_cf3035_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published_at', 'created_at'], name='blog_blogpo_publish_be3f2e_idx'),
        ),
    ]
