# Generated by Django 4.2.20 on 2025-10-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_add_database_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Канонический URL (опционально)'),
        ),
    ]
