# Generated by Django 5.0.14 on 2025-09-26 19:45

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_uk', models.CharField(max_length=255, verbose_name='Підзаголовок')),
                ('subtitle_en', models.CharField(max_length=255, verbose_name='Підзаголовок')),
                ('subtitle_ru', models.CharField(max_length=255, verbose_name='Підзаголовок')),
                ('title_uk', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('text_uk', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField()),
                ('photo', models.ImageField(upload_to='about_me/')),
            ],
            options={
                'verbose_name': 'О себе',
                'verbose_name_plural': 'О себе',
            },
        ),
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='background_videos/')),
            ],
            options={
                'verbose_name': 'Фоновое видео',
                'verbose_name_plural': 'Фоновые видео',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('phone_number_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_ua', models.CharField(max_length=255)),
                ('address_en', models.CharField(max_length=255)),
                ('address_ru', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Шапка профиля',
                'verbose_name_plural': 'Шапки профиля',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='services/')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uk', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.services')),
            ],
            options={
                'verbose_name': 'Описание услуги',
                'verbose_name_plural': 'Описание услуг',
            },
        ),
    ]
