# Generated by Django 5.0.14 on 2025-10-01 16:18

import ckeditor_uploader.fields
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_uk', models.CharField(max_length=255, verbose_name='Підзаголовок')),
                ('subtitle_en', models.CharField(max_length=255, verbose_name='Підзаголовок')),
                ('subtitle_ru', models.CharField(max_length=255, verbose_name='Підзаголовок')),
                ('title_uk', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('text_uk', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField()),
                ('photo', models.ImageField(upload_to='about_me/')),
            ],
            options={
                'verbose_name': 'О себе',
                'verbose_name_plural': 'О себе',
            },
        ),
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='background_videos/')),
            ],
            options={
                'verbose_name': 'Фоновое видео',
                'verbose_name_plural': 'Фоновые видео',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('phone_number_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_ua', models.CharField(max_length=255)),
                ('address_en', models.CharField(max_length=255)),
                ('address_ru', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Шапка профиля',
                'verbose_name_plural': 'Шапки профиля',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='services/')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('section', 'Раздел'), ('group', 'Группа'), ('page', 'Страница')], default='page', max_length=20, verbose_name='Тип элемента')),
                ('label_ua', models.CharField(max_length=255, verbose_name='Название (UA)')),
                ('label_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('label_en', models.CharField(max_length=255, verbose_name='Название (EN)')),
                ('nav_id', models.SlugField(max_length=255, unique=True, verbose_name='ID навигации')),
                ('slug_ua', models.SlugField(blank=True, max_length=255, verbose_name='URL slug (UA)')),
                ('slug_ru', models.SlugField(blank=True, max_length=255, verbose_name='URL slug (RU)')),
                ('slug_en', models.SlugField(blank=True, max_length=255, verbose_name='URL slug (EN)')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Показывать в меню')),
                ('component', models.CharField(blank=True, max_length=255, null=True, verbose_name='React компонент')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('description_ua', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание (UA)')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание (RU)')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание (EN)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main_page.servicecategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'label_ua'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uk', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.services')),
            ],
            options={
                'verbose_name': 'Описание услуги',
                'verbose_name_plural': 'Описание услуг',
            },
        ),
    ]
