# Generated by Django 5.0.14 on 2025-10-02 21:30

import django.db.models.deletion
import django_ckeditor_5.fields
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_uk', models.CharField(max_length=255, verbose_name='Підзаголовок')),
                ('subtitle_en', models.CharField(max_length=255, verbose_name='Підзаголовок')),
                ('subtitle_ru', models.CharField(max_length=255, verbose_name='Підзаголовок')),
                ('title_uk', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('text_uk', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('text_en', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('text_ru', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('photo', models.ImageField(upload_to='about_me/')),
            ],
            options={
                'verbose_name': 'О себе',
                'verbose_name_plural': 'О себе',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='background_videos/')),
            ],
            options={
                'verbose_name': 'Фоновое видео',
                'verbose_name_plural': 'Фоновые видео',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('phone_number_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_ua', models.CharField(max_length=255)),
                ('address_en', models.CharField(max_length=255)),
                ('address_ru', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Шапка профиля',
                'verbose_name_plural': 'Шапки профиля',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('service', models.CharField(choices=[('certification', 'Засвідчення копій документів та підписів'), ('realEstateTransactions', 'Нотаріальне супроводження угод з нерухомістю'), ('heritage', 'Оформлення спадщини та заповітів'), ('attorney', 'Посвідчення довіреностей та згод'), ('agreements', 'Посвідчення договорів купівлі-продажу, дарування, оренди')], max_length=50, verbose_name='Услуга')),
                ('rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicesFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('subtitle_uk', models.CharField(max_length=255)),
                ('subtitle_en', models.CharField(max_length=255)),
                ('subtitle_ru', models.CharField(max_length=255)),
                ('description_uk', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('description_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Для кого услуги',
                'verbose_name_plural': 'Для кого услуги',
            },
        ),
        migrations.CreateModel(
            name='VideoInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_video_uk', models.CharField(max_length=255)),
                ('title_video_en', models.CharField(max_length=255)),
                ('title_video_ru', models.CharField(max_length=255)),
                ('text_video_uk', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('text_video_en', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('text_video_ru', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('video', models.FileField(upload_to='video_interview/')),
            ],
            options={
                'verbose_name': 'Видео интервью',
                'verbose_name_plural': 'Видео интервью',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('section', 'Раздел'), ('group', 'Группа'), ('page', 'Страница')], default='page', max_length=20, verbose_name='Тип элемента')),
                ('label_ua', models.CharField(max_length=255, verbose_name='Название (UA)')),
                ('label_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('label_en', models.CharField(max_length=255, verbose_name='Название (EN)')),
                ('nav_id', models.SlugField(max_length=255, unique=True, verbose_name='ID навигации')),
                ('slug_ua', models.SlugField(blank=True, max_length=255, verbose_name='URL slug (UA)')),
                ('slug_ru', models.SlugField(blank=True, max_length=255, verbose_name='URL slug (RU)')),
                ('slug_en', models.SlugField(blank=True, max_length=255, verbose_name='URL slug (EN)')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Показывать в меню')),
                ('component', models.CharField(blank=True, max_length=255, null=True, verbose_name='React компонент')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('description_ua', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (UA)')),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (RU)')),
                ('description_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (EN)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main_page.servicecategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'label_ua'],
            },
        ),
    ]
