# Generated by Django 5.0.14 on 2025-10-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='header',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='telegram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='working_hours_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Working hours (EN)'),
        ),
        migrations.AddField(
            model_name='header',
            name='working_hours_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время работы (RU)'),
        ),
        migrations.AddField(
            model_name='header',
            name='working_hours_ua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Години роботи (UA)'),
        ),
        migrations.AddField(
            model_name='header',
            name='x_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='X (ex-Twitter)'),
        ),
        migrations.AlterModelTable(
            name='header',
            table='main_page_header',
        ),
    ]
