# Generated by Django 5.0.14 on 2025-09-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='background_videos/')),
            ],
            options={
                'verbose_name': 'Фоновое видео',
                'verbose_name_plural': 'Фоновые видео',
            },
        ),
    ]
