# Generated by Django 5.0.14 on 2025-10-13 14:10

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='telegram_url',
        ),
        migrations.RemoveField(
            model_name='header',
            name='whatsapp_url',
        ),
        migrations.AddField(
            model_name='header',
            name='telegram_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telegram телефон'),
        ),
        migrations.AddField(
            model_name='header',
            name='whatsapp_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='WhatsApp телефон'),
        ),
    ]
