# Generated by Django 4.2.20 on 2025-10-10 16:40

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('interview', 'Видео интервью'), ('about_me', 'Обо мне'), ('contacts', 'Как добраться до офиса')], max_length=20, unique=True, verbose_name='Тип видео блока')),
                ('title_ua', models.CharField(max_length=255, verbose_name='Заголовок (UA)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('description_ua', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (UA)')),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (RU)')),
                ('description_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (EN)')),
                ('video', models.FileField(upload_to='video_blocks/', verbose_name='Видеофайл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Видео блок',
                'verbose_name_plural': 'Видео блоки',
                'ordering': ['video_type'],
            },
        ),
    ]
