# Generated by Django 5.0.14 on 2025-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ua', models.CharField(max_length=255, verbose_name='Питання (UA)')),
                ('question_ru', models.CharField(max_length=255, verbose_name='Вопрос (RU)')),
                ('question_en', models.CharField(max_length=255, verbose_name='Question (EN)')),
                ('answer_ua', models.TextField(verbose_name='Відповідь (UA)')),
                ('answer_ru', models.TextField(verbose_name='Ответ (RU)')),
                ('answer_en', models.TextField(verbose_name='Answer (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Частый вопрос',
                'verbose_name_plural': 'Частые вопросы',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
