# Generated by Django 5.0.14 on 2025-10-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='show_mega_panel',
            field=models.BooleanField(default=True, verbose_name='Показывать в мега-панели'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='Показывать в меню'),
        ),
    ]
