# Generated by Django 5.0.14 on 2025-10-01 19:49

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description_ua',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (UA)'),
        ),
    ]
