# Generated by Django 5.0.14 on 2025-09-28 13:55

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('section', 'Раздел'), ('group', 'Группа'), ('page', 'Страница')], default='page', max_length=20, verbose_name='Тип элемента')),
                ('label_ua', models.CharField(max_length=255, verbose_name='Название (UA)')),
                ('label_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('label_en', models.CharField(max_length=255, verbose_name='Название (EN)')),
                ('nav_id', models.SlugField(max_length=255, unique=True, verbose_name='ID навигации')),
                ('slug_ua', models.SlugField(blank=True, max_length=255, verbose_name='URL slug (UA)')),
                ('slug_ru', models.SlugField(blank=True, max_length=255, verbose_name='URL slug (RU)')),
                ('slug_en', models.SlugField(blank=True, max_length=255, verbose_name='URL slug (EN)')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('component', models.CharField(blank=True, max_length=255, null=True, verbose_name='React компонент')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main_page.servicecategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'label_ua'],
            },
        ),
    ]
