# Generated by Django 5.0.14 on 2025-09-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_servicecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='Показывать в меню'),
        ),
    ]
