# Generated by Django 5.0.14 on 2025-10-07 18:32

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_header_options_header_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(choices=[('offer_agreement', 'Договір оферти'), ('privacy_policy', 'Політика конфіденційності'), ('trademark', 'Торгівельна марка')], max_length=64, unique=True, verbose_name='Тип документа')),
                ('title_ua', models.CharField(max_length=255, verbose_name='Заголовок (UA)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('content_ua', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент (UA)')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент (RU)')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент (EN)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Юридический документ',
                'verbose_name_plural': 'Юридические документы',
                'db_table': 'main_page_legal_document',
                'ordering': ['key'],
            },
        ),
    ]
