# Generated by Django 5.0.14 on 2025-10-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_servicecategory_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Бесплатная консультация',
                'verbose_name_plural': 'Бесплатные консультации',
                'ordering': ['-created_at'],
            },
        ),
    ]
