# Generated by Django 5.0.14 on 2025-09-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_backgroundvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_uk', models.CharField(max_length=255, verbose_name='Підзаголовок')),
                ('subtitle_en', models.CharField(max_length=255, verbose_name='Підзаголовок')),
                ('subtitle_ru', models.CharField(max_length=255, verbose_name='Підзаголовок')),
                ('title_uk', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('text_uk', models.TextField()),
                ('text_en', models.TextField()),
                ('text_ru', models.TextField()),
                ('photo', models.ImageField(upload_to='about_me/')),
            ],
        ),
    ]
