# Generated by Django 5.0.14 on 2025-10-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_videoblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoInterview',
        ),
    ]
