# Generated by Django 5.0.14 on 2025-10-18 11:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_trgm_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesfor',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='servicesfor',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='servicesfor',
            name='description_uk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (UA)'),
        ),
        migrations.AlterField(
            model_name='servicesfor',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesfor',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesfor',
            name='subtitle_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
