# Generated by Django 5.0.14 on 2025-10-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_servicesfor_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='contact_form_background/', verbose_name='Фоновое изображение')),
            ],
            options={
                'verbose_name': 'Фон формы обратной связи',
                'verbose_name_plural': 'Фоны форм обратной связи',
            },
        ),
    ]
