# Generated by Django 5.0.14 on 2025-10-08 12:43

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_legaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=255, verbose_name='Заголовок (UA)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('text_ua', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст (UA)')),
                ('text_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст (RU)')),
                ('text_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст (EN)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Блок про мене (детали)',
                'verbose_name_plural': 'Блоки про мене (детали)',
                'ordering': ['-created_at'],
            },
        ),
    ]
