# Generated by Django 5.0.14 on 2025-10-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_delete_videointerview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundvideo',
            options={'verbose_name': 'Фоновый медиа', 'verbose_name_plural': 'Фоновые медиа'},
        ),
        migrations.RemoveField(
            model_name='backgroundvideo',
            name='video_name',
        ),
        migrations.AddField(
            model_name='backgroundvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='background_videos/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='backgroundvideo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='backgroundvideo',
            name='media_type',
            field=models.CharField(choices=[('video', 'Видео'), ('image', 'Изображение')], default='video', max_length=10, verbose_name='Тип медиа'),
        ),
        migrations.AddField(
            model_name='backgroundvideo',
            name='name',
            field=models.CharField(default='Фоновое медиа', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='backgroundvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='background_videos/', verbose_name='Видеофайл'),
        ),
    ]
