# Generated by Django 5.0.14 on 2025-09-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_aboutme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'О себе', 'verbose_name_plural': 'О себе'},
        ),
    ]
