# Generated by Django 4.2.20 on 2025-09-28 13:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_aboutme_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='services/')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServicesFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('subtitle_uk', models.CharField(max_length=255)),
                ('subtitle_en', models.CharField(max_length=255)),
                ('subtitle_ru', models.CharField(max_length=255)),
                ('description_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Для кого услуги',
                'verbose_name_plural': 'Для кого услуги',
            },
        ),
        migrations.CreateModel(
            name='VideoInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_video_uk', models.CharField(max_length=255)),
                ('title_video_en', models.CharField(max_length=255)),
                ('title_video_ru', models.CharField(max_length=255)),
                ('text_video_uk', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_video_en', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_video_ru', ckeditor_uploader.fields.RichTextUploadingField()),
                ('video', models.FileField(upload_to='video_interview/')),
            ],
            options={
                'verbose_name': 'Видео интервью',
                'verbose_name_plural': 'Видео интервью',
            },
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='text_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uk', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.services')),
            ],
            options={
                'verbose_name': 'Описание услуги',
                'verbose_name_plural': 'Описание услуг',
            },
        ),
    ]
