# Generated by Django 5.0.14 on 2025-10-08 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_aboutmedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=255, verbose_name='Заголовок (UA)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Квалификация и опыт',
                'verbose_name_plural': 'Квалификация и опыт',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualificationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qualifications/certificates/')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='main_page.qualificationblock')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QualificationDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qualifications/diplomas/')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='main_page.qualificationblock')),
            ],
            options={
                'verbose_name': 'Свидетельство',
                'verbose_name_plural': 'Свидетельства',
                'ordering': ['order', 'id'],
            },
        ),
    ]
