# Generated by Django 4.2.20 on 2025-10-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_servicecategory_canonical_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='x_url',
        ),
        migrations.AddField(
            model_name='header',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='header',
            name='whatsapp_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='WhatsApp'),
        ),
    ]
