# Generated by Django 4.2.20 on 2025-09-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_contactrequest_review_reviewformsubmission_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactRequest',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewFormSubmission',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
