# Generated by Django 5.0.14 on 2025-09-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_application_services_servicesfor_videointerview_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDescription',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
