# Generated by Django 5.0.14 on 2025-09-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_aboutme_text_en_alter_aboutme_text_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('service', models.CharField(choices=[('certification', 'Засвідчення копій документів та підписів'), ('realEstateTransactions', 'Нотаріальне супроводження угод з нерухомістю'), ('heritage', 'Оформлення спадщини та заповітів'), ('attorney', 'Посвідчення довіреностей та згод'), ('agreements', 'Посвідчення договорів купівлі-продажу, дарування, оренди')], max_length=50, verbose_name='Услуга')),
                ('rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
